### ISSUE TITLE
sendtoal

### ISSUE THREAD

**Issue by JeysonSK** [ProxioDev/ValioBungee#101]
### intended behavior

Hello, when I use the /sendtoall command, it sends the command to all proxies, except the one where I am issuing the command.
(example: I do /sendtoall alert test, on proxy1, proxy2 & 3 receive the alert, but proxy1 does not alert.)

### what the behavior you actually saw

execution of the command only on proxy2 and proxy3

### Steps to reproduce

........

### Velocity or Bungeecord Versions

This server is running BungeeCord version git:BungeeCord-Bootstrap:1.20-R0.3-SNAPSHOT:18eae8a:1842 by md_5

### RedisBungee Version & Redis Version

========================================
RedisBungee version: 0.12.2
Commit: e1d40163
========================================

**Comment by ham1255** [comment]
fixed

**Comment by ham1255** [comment]
download 0.12.4 from here https://github.com/ProxioDev/ValioBungee/actions/runs/9103735878

**Comment by JeysonSK** [comment]
it's good

**Comment by ham1255** [comment]
oops a mistake
