### ISSUE TITLE
incompatibility with minimotd

### ISSUE THREAD

**Issue by Incluuu** [ProxioDev/ValioBungee#107]
### intended behavior

redisbungee does not allow fakeplayers with minimotd

### what the behavior you actually saw

        fake-players="100%"
        # Enable fake player count feature
        fake-players-enabled=true

this option do not work when ""handle-motd: true"" is enabled

### Steps to reproduce

1. Install 2 proxy velocity
2. synchronize 2 proxy with redis
3. install minimotd and enable fakeplayers

### Velocity or Bungeecord Versions

velocity #399

### RedisBungee Version & Redis Version

redisbungee version: 0.12.4
redis version: 7.2.5

**Comment by ham1255** [comment]
This is not problem is not fix since minimotd need to support the plugin
