### ISSUE TITLE
Having a slight issue on plugin start up.

### ISSUE THREAD

**Issue by EiDevv** [ProxioDev/ValioBungee#110]
### Your question?

I have followed the guide on how to setup Redis, i setup the data base ect. But as soon as i start both of my proxies an error like this pops up in console [latest (1).log](https://github.com/user-attachments/files/16070706/latest.1.log)

I read through what the error was and was wonder did i perhaps set Redis Bungee up wrongly?

Heres the config.
[config (1).txt](https://github.com/user-attachments/files/16071348/config.1.txt)

I am using 'RedisBungee-Proxy-Velocity-0.12.4-all.jar'
And operation on 'Velocity 3.3.0-SNAPSHOT'

**Comment by ham1255** [comment]
Sorry for late response but it seems like you either set the password wrong which throws  `NOAUTH Authentication required`
