### ISSUE TITLE
The last online cache is delayed

### ISSUE THREAD

**Issue by md5nake** [ProxioDev/ValioBungee#97]
### intended behavior

I expect `RedisBungeeAPI.getRedisBungeeApi().getLastOnline(uuid)` to return 0 when a player is online.

### what the behavior you actually saw

It instead returns a timestamp, which also breaks `RedisBungeeAPI.getRedisBungeeApi().isPlayerOnline(uuid)`.

### Steps to reproduce

Run `RedisBungeeAPI.getRedisBungeeApi().getLastOnline(uuid)` whilst a player is online. It does not return 0.

### Velocity or Bungeecord Versions

Velocity 3.3.0-SNAPSHOT

### RedisBungee Version & Redis Version

Redis version 7.0.5
RedisBungee version: 0.12.1

**Comment by ham1255** [comment]
i gotta admit that i forgot why i was caching the player last online
